// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSy9w0gQXjKNy2Wa_akVdg8_ygGrET0O8',
    appId: '1:836239782997:web:0a95d1d8e216e93c8110dc',
    messagingSenderId: '836239782997',
    projectId: 'ezproject-a714d',
    authDomain: 'ezproject-a714d.firebaseapp.com',
    storageBucket: 'ezproject-a714d.firebasestorage.app',
    measurementId: 'G-PV3C1B0RD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE4PsnPT9erVieqT7CrOlKB21q76rdNWY',
    appId: '1:836239782997:android:ad9e4298c85c267b8110dc',
    messagingSenderId: '836239782997',
    projectId: 'ezproject-a714d',
    storageBucket: 'ezproject-a714d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0CdvEy4KJ66vdOX0fccs-yYw5PJarmc8',
    appId: '1:836239782997:ios:ac976d87cb7525768110dc',
    messagingSenderId: '836239782997',
    projectId: 'ezproject-a714d',
    storageBucket: 'ezproject-a714d.firebasestorage.app',
    iosBundleId: 'com.example.mapAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0CdvEy4KJ66vdOX0fccs-yYw5PJarmc8',
    appId: '1:836239782997:ios:ac976d87cb7525768110dc',
    messagingSenderId: '836239782997',
    projectId: 'ezproject-a714d',
    storageBucket: 'ezproject-a714d.firebasestorage.app',
    iosBundleId: 'com.example.mapAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSy9w0gQXjKNy2Wa_akVdg8_ygGrET0O8',
    appId: '1:836239782997:web:854d5ca0862c7c788110dc',
    messagingSenderId: '836239782997',
    projectId: 'ezproject-a714d',
    authDomain: 'ezproject-a714d.firebaseapp.com',
    storageBucket: 'ezproject-a714d.firebasestorage.app',
    measurementId: 'G-WH9VN9NMLJ',
  );
}
